"""
Файл аналізатор для сервісу 1
"""

import json
import os

from langchain_core.prompts import ChatPromptTemplate
from langchain_ollama import OllamaLLM

# Шлях до файлів(у нашому випадку json)
FILE1_PATH = 'FILE1.json'
FILE2_PATH = 'FILE2.json'

# Налаштування шаблону та моделі
template = """
You are an expert in legal document analysis, specializing in identifying changes in financial regulations such as tax rates, fees, and commissions. You are provided with two documents: FILE-1 and FILE-2, both containing information about enacted laws. Your task is to compare these documents and identify any changes related to the following:

- Changes in tax rates
- Introduction or modification of fees and commissions
- Any other financial-related amendments

After analyzing the documents, provide a list of all identified changes with a brief description for each.

Here are the details:

FILE-1: {file_1_content}
FILE-2: {file_2_content}

Identified Changes:
• change_1_description
• change_2_description
• change_3_description
...
"""


# Функція, яка використовується для завантаження json-файлу
def load_file(path):
    """Завантаження контексту з файлу."""
    if os.path.exists(path):
        with open(path, 'r') as f:
            return json.load(f)
    return {}


model = OllamaLLM(model='llama3')
prompt = ChatPromptTemplate.from_template(template)
chain = prompt | model


# Сама функція аналізу файлів і повернення потрібного результату
def analize() -> str:
    file_1 = load_file(FILE1_PATH)
    print("Successfully uploaded file1")
    file_2 = load_file(FILE2_PATH)
    print("Successfully uploaded file2")

    file_1_context = file_1.get('text', "")
    file_2_context = file_2.get('text', "")

    # Генерація відповіді з використанням моделі
    result = chain.invoke({"file_1_content": file_1_context, "file_2_content": file_2_context})

    print('Generation was finished')
    return result


resulting = analize()
print(resulting)


"""Це є вхідні дані, які подавалися"""
"""
Tax Policy Act 2023

Section 1:
The corporate income tax rate is hereby established at 20% of the total profit. This tax applies to all corporations operating within the jurisdiction and is calculated based on net income after allowable deductions. The intention of this tax is to ensure a fair contribution from profitable enterprises towards public services.

Section 2:
The value-added tax (VAT) is hereby established at a rate of 15% on all goods and services. This VAT is applied at each stage of the production and distribution chain, ensuring that the tax burden is distributed equitably. Exemptions to this tax include essential goods such as foodstuffs and medical supplies.

Section 3:
An excise tax on alcoholic beverages is established at 25% of the retail price. This excise tax is intended to discourage excessive consumption of alcohol and to provide additional revenue for public health initiatives.

Section 4:
A commission for domestic bank transfers is set at 2% of the transfer amount. This commission is charged by financial institutions for the processing of electronic payments and is intended to cover the costs associated with maintaining the payment infrastructure.

Section 5:
A property tax is established at 1% of the assessed value of real estate. This tax is levied annually and is based on the market value of the property as determined by local government assessors. The funds collected from this tax are allocated to local public services, including schools, roads, and emergency services.

Section 6:
No changes shall be made to the existing tax rates or structures without a formal review and approval by the legislative committee responsible for fiscal matters. Any amendments to the tax rates or the introduction of new taxes must be justified by a thorough analysis of the economic impact on both businesses and consumers.

"""

"""
Tax Policy Act 2024

Section 1:
The corporate income tax rate is hereby adjusted to 22% of the total profit. This change reflects the government's commitment to maintaining a balanced budget while ensuring that corporations contribute their fair share to public finances. The additional revenue generated by this increase will be allocated to healthcare and education sectors.

Section 2:
The value-added tax (VAT) is revised to 17% on all goods and services. This adjustment is aimed at addressing the growing fiscal deficit and ensuring the sustainability of public finances. The exemptions for essential goods remain unchanged, ensuring that basic needs are not disproportionately affected by this increase.

Section 3:
The excise tax on alcoholic beverages is increased to 27% of the retail price. This measure is part of a broader public health strategy to reduce alcohol consumption and its associated social harms. The additional revenue will support addiction treatment programs and public health campaigns.

Section 4:
The commission for domestic bank transfers is increased to 2.5% of the transfer amount. This change is intended to reflect the rising costs of maintaining secure and efficient payment systems. Financial institutions are required to disclose this fee to customers at the time of transaction.

Section 5:
The property tax is adjusted to 1.5% of the assessed value of real estate. This increase is part of a broader effort to align property taxes with market values and to provide additional funding for local government services. The tax will continue to be levied annually, with the next reassessment scheduled for 2025.

Section 6:
All changes to the tax code must be reviewed annually by the fiscal oversight committee to ensure compliance with national economic goals. Any further adjustments to tax rates will be subject to public consultation and economic impact analysis before implementation.
"""
